name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'Secret is ${{ secrets }}.'

      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: date +%s > report2.txt

      - uses: Brightspace/third-party-actions@actions/checkout

      - name: Commit npm version bump
        run: |
          git fetch origin
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git branch
          git checkout ccisse_other
          git merge origin/master
          date +%s > report2.txt
          git add .
          git commit -am "Npm version bump"
          git push -f origin ccisse_other

      - name: Pull Request
        uses: Brightspace/third-party-actions@actions/github-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { data: newPr } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Dependabots Weekly Updates',
              head: 'refs/heads/ccisse_other',
              base: 'refs/heads/master',
              label: 'Triage'
            });
            github.issues.createComment({
              issue_number: newPr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `PR #${newPr.number} created for prettier JavaScript.`
            });
  
