name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'Secret is ${{ secrets }}.'

      - name: Test Action
        uses: neverendingqs/gh-action-node-bump-version-pr@v1.1.0
        with:
          bump-version: patch
          description: "Hello this is a description"

      - name: Test Action other action
        uses: actions/checkout@v2
        ref: ccisse_test

      - name: Test Action other action
        uses: peter-evans/create-pull-request@v3
        base: master    # the name of your default branch based on your PR changes here
        branch: ccisse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
