name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'Secret is ${{ secrets }}.'

      - name: Test Action other action
        uses: actions/checkout@v2
        with: 
          ref: ccisse_test

      - name: Check diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch
          git diff origin/ccisse_other..origin/master --shortstat
          VAR2=$(git diff origin/ccisse_other..origin/master --shortstat)
          echo $VAR2
        id: hello2

      - name: Check diff 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch
          git diff origin/master..origin/master --shortstat
          VAR1=$(git diff origin/master..origin/master --shortstat)
          echo $VAR1
          if git diff --exit-code origin/master..origin/master --shortstat > /dev/null
          echo "The image id is up to date"
          then exit 1
          fi
          echo "Hello"
        id: hello22

